name: build.yml

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Spigot build workflow run ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download artifacts
      run: |
        gh workflow list
        OTHER_REPO="juliengriffoul/spigot.build"
        WF_NAME="build.yml"
        ARTIFACT_NAME="spigot"
        RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
        gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        # List the artifiact directory/files
        ls -lR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Unzip artifacts
      run: |
        unzip artifacts.zip
        mv spigot-*.jar spigot.jar

    - name: Build image
      run: docker build . --file Dockerfile --tag spigot-server:latest
