name: build.yml

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Spigot build workflow run ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Download artifact
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        REPOSITORY="juliengriffoul/spigot.build"
        WORKFLOW="build.yml"
        # RUN_ID=`gh run --repo ${REPOSITORY} list --workflow ${WORKFLOW} --json databaseId --jq .[0].databaseId`
        gh run --repo ${REPOSITORY} download ${{ github.event.inputs.run_id }} -n spigot
        ls -lR

    - name: Rename artifact
      run: |
        mv spigot-*.jar spigot.jar

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.event.inputs.run_id }}
          ghcr.io/${{ github.repository }}:latest
