name: build.yml

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Spigot build workflow run ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        REPOSITORY="juliengriffoul/spigot.build"
        WORKFLOW="build.yml"
        # RUN_ID=`gh run --repo ${REPOSITORY} list --workflow ${WORKFLOW} --json databaseId --jq .[0].databaseId`
        gh run --repo ${REPOSITORY} download ${{ github.event.inputs.run_id }} -n spigot
        ls -lR

    - name: Build image
      run: |
        mv spigot-*.jar spigot.jar
        docker build . --file Dockerfile --tag spigot-server:latest
